version: 4.3.2
name: Devbro Rust webframework
description: test content 
url: https://devbro.com
repository: https://github.com/devbro1/rust_web_framework
timezone: America/Toronto
relative_permalinks: false
show_downloads: true
theme: jekyll-theme-cayman

markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons